## Basic Configuration

baseurl = "https://kato-sotaro.github.io/"
builddrafts = false
canonifyurls = false
languageCode = "utf-8"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Kato Sotaro"
title = "Kato Sotaro"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Sotaro Kato"
intro = "Greeting is the Most important"
description = "Data Scientist　(domain:finance)"
authorimage = "my_hp_photo_7.jpg"
dateformat = "DEC 2, 2019"

## Site Meta Settings
[params.meta]
description = "Kato Sotaro's blog"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "kato-sotaro"
instagram = "<username>"
twitter = "<username>"
facebook = "<username>"
stackoverflow = "katosotaro"
tumblr = "<username>"#ウェブデザイン
email = "katosotaro18@gmail.com"

## Extras
[params.extra]
copyright = "© 2019. Kato Sotaro. [All Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"
